2.import laibraris

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import pymysql
from sqlalchemy import create_engine

3.load datadet

In [7]:
df=pd. read_csv("/Users/dipanshuthakur/Desktop/Walmart-project/Walmart.csv",encoding="latin1")
print(df)

       invoice_id   Branch         City                category unit_price  \
0               1  WALM003  San Antonio       Health and beauty     $74.69
1               2  WALM048    Harlingen  Electronic accessories     $15.28
2               3  WALM067  Haltom City      Home and lifestyle     $46.33
3               4  WALM064      Bedford       Health and beauty     $58.22
4               5  WALM013       Irving       Sports and travel     $86.31
...           ...      ...          ...                     ...        ...
10046        9996  WALM056      Rowlett     Fashion accessories        $37
10047        9997  WALM030   Richardson      Home and lifestyle        $58
10048        9998  WALM050     Victoria     Fashion accessories        $52
10049        9999  WALM032        Tyler      Home and lifestyle        $79
10050       10000  WALM069     Rockwall     Fashion accessories        $62

       quantity      date      time payment_method  rating  profit_margin
0           7.0  05/01/19  13:08:00        Ewallet     9.1           0.48
1           5.0  08/03/19  10:29:00           Cash     9.6           0.48
2           7.0  03/03/19  13:23:00    Credit card     7.4           0.33
3           8.0  27/01/19  20:33:00        Ewallet     8.4           0.33
4           7.0  08/02/19  10:37:00        Ewallet     5.3           0.48
...         ...       ...       ...            ...     ...            ...
10046       3.0  03/08/23  10:10:00           Cash     3.0           0.33
10047       2.0  22/02/21  14:20:00           Cash     7.0           0.48
10048       3.0  15/06/23  16:00:00    Credit card     4.0           0.48
10049       2.0  25/02/21  12:25:00           Cash     7.0           0.48
10050       3.0  26/09/20   9:48:00           Cash     3.0           0.33

[10051 rows x 11 columns]

4.understanding the dataset

In [8]:
df.head()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin
0,1,WALM003,San Antonio,Health and beauty,$74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48
1,2,WALM048,Harlingen,Electronic accessories,$15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48
2,3,WALM067,Haltom City,Home and lifestyle,$46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33
3,4,WALM064,Bedford,Health and beauty,$58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33
4,5,WALM013,Irving,Sports and travel,$86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48

In [9]:
df.tail(10)

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin
10041,9991,WALM074,Weslaco,Home and lifestyle,$35,3.0,09/07/20,6:38:00,Cash,5.0,0.33
10042,9992,WALM087,Waxahachie,Fashion accessories,$48,3.0,09/09/23,10:54:00,Cash,6.0,0.33
10043,9993,WALM073,Seguin,Home and lifestyle,$31,2.0,01/11/23,15:21:00,Cash,5.0,0.33
10044,9994,WALM055,Waxahachie,Fashion accessories,$34,1.0,29/04/23,14:34:00,Cash,6.0,0.33
10045,9995,WALM030,Richardson,Home and lifestyle,$62,1.0,15/02/21,9:04:00,Cash,3.0,0.48
10046,9996,WALM056,Rowlett,Fashion accessories,$37,3.0,03/08/23,10:10:00,Cash,3.0,0.33
10047,9997,WALM030,Richardson,Home and lifestyle,$58,2.0,22/02/21,14:20:00,Cash,7.0,0.48
10048,9998,WALM050,Victoria,Fashion accessories,$52,3.0,15/06/23,16:00:00,Credit card,4.0,0.48
10049,9999,WALM032,Tyler,Home and lifestyle,$79,2.0,25/02/21,12:25:00,Cash,7.0,0.48
10050,10000,WALM069,Rockwall,Fashion accessories,$62,3.0,26/09/20,9:48:00,Cash,3.0,0.33

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10051 entries, 0 to 10050
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_id      10051 non-null  int64
 1   Branch          10051 non-null  object
 2   City            10051 non-null  object
 3   category        10051 non-null  object
 4   unit_price      10020 non-null  object
 5   quantity        10020 non-null  float64
 6   date            10051 non-null  object
 7   time            10051 non-null  object
 8   payment_method  10051 non-null  object
 9   rating          10051 non-null  float64
 10  profit_margin   10051 non-null  float64
dtypes: float64(3), int64(1), object(7)
memory usage: 863.9+ KB

In [11]:
df.shape

(10051, 11)

In [12]:
df.columns

Index(['invoice_id', 'Branch', 'City', 'category', 'unit_price', 'quantity',
       'date', 'time', 'payment_method', 'rating', 'profit_margin'],
      dtype='object')

In [13]:
df.describe()

         invoice_id      quantity        rating  profit_margin
count  10051.000000  10020.000000  10051.000000   10051.000000
mean    5025.741220      2.353493      5.825659       0.393791
std     2901.174372      1.602658      1.763991       0.090669
min        1.000000      1.000000      3.000000       0.180000
25%     2513.500000      1.000000      4.000000       0.330000
50%     5026.000000      2.000000      6.000000       0.330000
75%     7538.500000      3.000000      7.000000       0.480000
max    10000.000000     10.000000     10.000000       0.570000

5.data cleaning

REMOVING DUPLICATED VALUES

In [14]:
#all duplicates
df.duplicated().sum()

np.int64(51)

In [15]:
#removing duplicates
df.drop_duplicates(inplace=True)

In [16]:
df.duplicated().sum()

np.int64(0)

In [17]:
df.shape

(10000, 11)

HANDLING MISSING /NULL VALUES

In [18]:
#shows how many null are there in a column
df.isnull().sum()

invoice_id         0
Branch             0
City               0
category           0
unit_price        31
quantity          31
date               0
time               0
payment_method     0
rating             0
profit_margin      0
dtype: int64

In [19]:
#droping all  rows with missing values
df.dropna(inplace=True)

In [20]:
df.isnull().sum()

invoice_id        0
Branch            0
City              0
category          0
unit_price        0
quantity          0
date              0
time              0
payment_method    0
rating            0
profit_margin     0
dtype: int64

In [21]:
df.shape

(9969, 11)

CORRRECT DATA TYPES

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9969 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_id      9969 non-null   int64
 1   Branch          9969 non-null   object
 2   City            9969 non-null   object
 3   category        9969 non-null   object
 4   unit_price      9969 non-null   object
 5   quantity        9969 non-null   float64
 6   date            9969 non-null   object
 7   time            9969 non-null   object
 8   payment_method  9969 non-null   object
 9   rating          9969 non-null   float64
 10  profit_margin   9969 non-null   float64
dtypes: float64(3), int64(1), object(7)
memory usage: 934.6+ KB

In [25]:
df.dtypes

invoice_id          int64
Branch             object
City               object
category           object
unit_price         object
quantity          float64
date               object
time               object
payment_method     object
rating            float64
profit_margin     float64
dtype: object

In [28]:
df['unit_price'].str.replace('$','')

0       74.69
1       15.28
2       46.33
3       58.22
4       86.31
        ...
9995       37
9996       58
9997       52
9998       79
9999       62
Name: unit_price, Length: 9969, dtype: object

In [31]:
df['unit_price'] = df['unit_price'].str.replace('$','').astype(float)
df.head()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin
0,1,WALM003,San Antonio,Health and beauty,74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48
1,2,WALM048,Harlingen,Electronic accessories,15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48
2,3,WALM067,Haltom City,Home and lifestyle,46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33
3,4,WALM064,Bedford,Health and beauty,58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33
4,5,WALM013,Irving,Sports and travel,86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48

In [32]:
df.info

<bound method DataFrame.info of       invoice_id   Branch         City                category  unit_price  \
0              1  WALM003  San Antonio       Health and beauty       74.69
1              2  WALM048    Harlingen  Electronic accessories       15.28
2              3  WALM067  Haltom City      Home and lifestyle       46.33
3              4  WALM064      Bedford       Health and beauty       58.22
4              5  WALM013       Irving       Sports and travel       86.31
...          ...      ...          ...                     ...         ...
9995        9996  WALM056      Rowlett     Fashion accessories       37.00
9996        9997  WALM030   Richardson      Home and lifestyle       58.00
9997        9998  WALM050     Victoria     Fashion accessories       52.00
9998        9999  WALM032        Tyler      Home and lifestyle       79.00
9999       10000  WALM069     Rockwall     Fashion accessories       62.00

      quantity      date      time payment_method  rating  profit_margin
0          7.0  05/01/19  13:08:00        Ewallet     9.1           0.48
1          5.0  08/03/19  10:29:00           Cash     9.6           0.48
2          7.0  03/03/19  13:23:00    Credit card     7.4           0.33
3          8.0  27/01/19  20:33:00        Ewallet     8.4           0.33
4          7.0  08/02/19  10:37:00        Ewallet     5.3           0.48
...        ...       ...       ...            ...     ...            ...
9995       3.0  03/08/23  10:10:00           Cash     3.0           0.33
9996       2.0  22/02/21  14:20:00           Cash     7.0           0.48
9997       3.0  15/06/23  16:00:00    Credit card     4.0           0.48
9998       2.0  25/02/21  12:25:00           Cash     7.0           0.48
9999       3.0  26/09/20   9:48:00           Cash     3.0           0.33

[9969 rows x 11 columns]>

Fix inconsistent values

ADDING A NEW COLUMN

In [ ]:
df['total']=df['unit_price']*df['quantity']
df.head()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin,total
0,1,WALM003,San Antonio,Health and beauty,74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48,522.83
1,2,WALM048,Harlingen,Electronic accessories,15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48,76.40
2,3,WALM067,Haltom City,Home and lifestyle,46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33,324.31
3,4,WALM064,Bedford,Health and beauty,58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33,465.76
4,5,WALM013,Irving,Sports and travel,86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48,604.17

✅DATA EXPLORATION AND LEADING

#importing dependencies
#my sql tool kit
#pymysql#this will work as adaptor
#sqlalchemy create_engine
#but i have anaconda enviroment so dont need to install it again

In [ ]:
#mysql
#host = localhost
#port = 3306
#user = root
#password = dipanshu123

In [ ]:
df.shape

(9969, 12)

In [ ]:
#mysql conection
# "mysql+pymysql://user:password@localhost:3306/db_name"
engine_mysql = create_engine("mysql+pymysql://root:dipanshu123@localhost:3306/walmart_db")
try:
    engine_mysql
    print("connection succesed to mysql")
except:
    print("unable to connect")

connection succesed to mysql

In [ ]:
df.to_sql(name='walmart_db',con=engine_mysql,if_exists='replace',index=False)

9969

In [ ]:
df.shape

(9969, 11)

In [33]:
df.to_csv("cleaned_walmart_data.csv", index=False)